package com.yt.model;

import com.yt.model.users1;

public interface users1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    int insert(users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    int insertSelective(users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    users1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    int updateByPrimaryKeySelective(users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Feb 25 14:17:29 CST 2016
     */
    int updateByPrimaryKey(users1 record);
}